### ISSUE TITLE
investigate: https://static.rust-lang.org/manifests.txt has not been updated since 2020-02-23

### ISSUE THREAD

**Issue by foresterre** [foresterre/rust-releases#9]
Affects: `ChannelManifests` source
See also: https://github.com/rust-lang/rust/issues/56971#issuecomment-532783994

The 'new' dist index which was created because of https://github.com/rust-lang/rust/issues/56971, has not seen an update since 2020-02-23. I missed this while implementing the `ChannelManifests` source, and it's a bit unfortunate because it offered a solid path to include beta and nightly releases as well.

**Comment by jethrogb** [comment]
Presumably due to https://github.com/rust-lang/generate-manifest-list/issues/2

**Comment by foresterre** [comment]
Thanks for sharing!

**Comment by Mark-Simulacrum** [comment]
FYI - manifests.txt should now be fixed, hopefully in a reliable way.

**Comment by foresterre** [comment]
> 
> 
> FYI - manifests.txt should now be fixed, hopefully in a reliable way.

Awesome! Thanks for letting me know!
